import {draw,commands} from './assembler.mjs';
const $=s=>document.querySelector(s);
const [skin,library]=await Promise.all(['hero/skin.json','rig/poses.json'].map(p=>fetch(p).then(r=>r.json())));
const sheet=new Image();sheet.src='hero/parts.png';await sheet.decode();const images={sheet};
let selected=null;
$('#state').innerHTML=library.states.map(s=>`<option value="${s.destroyMask}">${s.id} · ${s.pose}</option>`).join('');
const canvases=[];
function paint(canvas,state,options={}){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();const scale=canvas.width/105;ctx.translate(canvas.width/2,canvas.height*.79);ctx.scale(scale,scale);draw(ctx,skin,state,images,options);ctx.restore()}
function show(){const state=library.states[+$('#state').value];paint($('#preview'),state,{wire:$('#wire').checked,onlyRig:$('#only-rig').checked,explode:+$('#explode').value,selected});$('#info').textContent=`${state.id} · ${state.pose} · ${state.visibleParts.join(' / ')} · 头胸腹伤效 ${state.injuryLayers.map(l=>l.part).join(' / ')||'无'}`;$('#angles').textContent=JSON.stringify(state.nodes.map(n=>({id:n.id,visible:n.visible,localEulerXYZDeg:n.localEulerXYZDeg,localMatrix:n.localMatrix,worldMatrix:n.worldMatrix})),null,2)}
function refreshAll(){canvases.forEach((canvas,i)=>paint(canvas,library.states[i]));show()}
for(const state of library.states){const b=document.createElement('button'),canvas=document.createElement('canvas'),label=document.createElement('span');canvas.width=432;canvas.height=384;label.textContent=state.id+' · '+state.pose;b.append(canvas,label);b.onclick=()=>{$('#state').value=state.destroyMask;show();$('#preview').scrollIntoView({behavior:'smooth'})};$('#all').append(b);canvases.push(canvas)}
for(const m of skin.modules){const card=document.createElement('div');card.className='part';const canvas=document.createElement('canvas');canvas.width=140;canvas.height=130;const ctx=canvas.getContext('2d'),c=m.crop,f=Math.min(130/c[2],120/c[3]);ctx.drawImage(sheet,...c,(140-c[2]*f)/2,(130-c[3]*f)/2,c[2]*f,c[3]*f);const button=document.createElement('button');button.textContent=m.name;button.onclick=()=>{selected=selected===m.id?null:m.id;show()};const a=document.createElement('a');a.href='hero/'+m.wrapper;a.textContent='单独查看';a.target='_blank';const label=document.createElement('label');label.textContent='替换 '+c[2]+'×'+c[3]+' 透明图';const input=document.createElement('input');input.type='file';input.accept='image/png,image/webp';input.onchange=async()=>{const file=input.files[0];if(!file)return;const url=URL.createObjectURL(file),im=new Image();try{im.src=url;await im.decode();if(im.width!==c[2]||im.height!==c[3])throw new Error('尺寸必须保持 '+c[2]+'×'+c[3]);images[m.id]=im;$('#upload-status').textContent=m.name+'已替换，128种状态同步复用。';refreshAll()}catch(e){$('#upload-status').textContent=e.message}finally{URL.revokeObjectURL(url)}};label.append(input);card.append(canvas,button,a,label);$('#parts').append(card)}
for(const id of ['state','wire','only-rig','explode'])$('#'+id).oninput=show;
$('#previous').onclick=()=>{$('#state').value=(+$('#state').value+127)%128;show()};$('#next').onclick=()=>{$('#state').value=(+$('#state').value+1)%128;show()};
$('#reset').onclick=()=>{for(const key of Object.keys(images))if(key!=='sheet')delete images[key];$('#upload-status').textContent='已恢复主角部件';refreshAll()};
$('#export').onclick=()=>{const state=library.states[+$('#state').value],canvas=document.createElement('canvas');canvas.width=840;canvas.height=720;paint(canvas,state);const a=document.createElement('a');a.download=skin.id+'-'+state.id+'.png';a.href=canvas.toDataURL();a.click()};
$('#state').value=Math.max(0,Math.min(127,Number(new URLSearchParams(location.search).get('state'))||0));
refreshAll();
